# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0067_auto_20170123_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='backing',
            name='users',
            field=models.ManyToManyField(related_name='backings', to=settings.AUTH_USER_MODEL),
        ),
    ]
