# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 01:37
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20170123_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backing',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='profile_image',
            field=models.ImageField(blank=True, help_text=b'A shiny high profile image for the location. Must be 336x344px.', null=True, upload_to=core.models.location_img_upload_to),
        ),
    ]
