# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20190202_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationimage',
            name='baseimage_ptr',
        ),
        migrations.RemoveField(
            model_name='locationimage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='baseimage_ptr',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='resource',
        ),
        migrations.DeleteModel(
            name='BaseImage',
        ),
        migrations.DeleteModel(
            name='LocationImage',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
