# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_backing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backing',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backing', to='core.Resource'),
        ),
    ]
