# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 22:55
from __future__ import unicode_literals

import modernomad.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_fix_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_time_deprecated',
            field=models.CharField(blank=True, help_text='Optional, if known', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrive_deprecated',
            field=models.DateField(null=True, verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Any additional comments. (Optional)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='depart_deprecated',
            field=models.DateField(null=True, verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_deprecated',
            field=models.TextField(null=True, verbose_name='Tell us a bit about the reason for your trip/stay'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Uses the default rate unless otherwise specified.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_deprecated',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('house declined', 'House Declined'), ('user declined', 'User Declined'), ('canceled', 'Canceled')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tags_deprecated',
            field=models.CharField(blank=True, help_text='What are 2 or 3 tags that characterize this trip?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(verbose_name='The body of the email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='context',
            field=models.CharField(choices=[('booking', 'Booking'), ('subscription', 'Subscription')], max_length=32),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Template Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Default Subject Line'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Fee Name'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='percentage',
            field=models.FloatField(default=0, help_text='For example 5.2% = 0.052'),
        ),
        migrations.AlterField(
            model_name='location',
            name='announcement',
            field=models.TextField(blank=True, default='This is far left of three sections underneath the main landing page text to use for announcements and news. HTML is supported.', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bank_account_number',
            field=models.IntegerField(blank=True, help_text='We use this to transfer money to you!', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bank_name',
            field=models.CharField(blank=True, help_text='We use this to transfer money to you!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='check_in',
            field=models.CharField(help_text='When your guests can expect their bed to be ready.', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='check_out',
            field=models.CharField(help_text='When your guests should be out of their bed/room.', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='email_subject_prefix',
            field=models.CharField(help_text='Your prefix will be wrapped in square brackets automatically.', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='front_page_participate',
            field=models.TextField(default='This is far right of three sections underneath the main landing page text to tell people how to get involved with your community. There is a link to the Events page underneath. HTML is supported. '),
        ),
        migrations.AlterField(
            model_name='location',
            name='front_page_stay',
            field=models.TextField(default='This is the middle of three sections underneath the main landing page text to entice people to stay with you, and then links to the stay page (above). HTML is supported.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(help_text='Requires an image with proportions 800px wide x 225px high', upload_to=modernomad.core.models.location_img_upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='name_on_account',
            field=models.CharField(blank=True, help_text='We use this to transfer money to you!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='A shiny high profile image for the location. Must be 336x344px.', null=True, upload_to=modernomad.core.models.location_img_upload_to),
        ),
        migrations.AlterField(
            model_name='location',
            name='readonly_admins',
            field=models.ManyToManyField(blank=True, help_text='Readonly admins do not show up as part of the community. Useful for eg. external bookkeepers, etc.', related_name='readonly_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='routing_number',
            field=models.IntegerField(blank=True, help_text='We use this to transfer money to you!', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(help_text='Try to make this short and sweet. It will also be used to form several location-specific email addresses in the form of xxx@<your_slug>.mail.embassynetwork.com', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='stay_page',
            field=models.TextField(default='This is the page which has some descriptive text at the top (this text), and then lists the available rooms. HTML is supported.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(help_text='Must be an accurate timezone name, eg. "America/Los_Angeles". Check here for your time zone: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('link', 'Those with the Link')], default='link', max_length=32),
        ),
        migrations.AlterField(
            model_name='locationemailtemplate',
            name='html_body',
            field=models.TextField(blank=True, null=True, verbose_name='The html body of the email'),
        ),
        migrations.AlterField(
            model_name='locationemailtemplate',
            name='key',
            field=models.CharField(choices=[('admin_daily_update', 'Admin Daily Update'), ('guest_daily_update', 'Guest Daily Update'), ('invoice', 'Invoice'), ('receipt', 'Booking Receipt'), ('subscription_receipt', 'Subscription Receipt'), ('newbooking', 'New Booking'), ('pre_arrival_welcome', 'Pre-Arrival Welcome'), ('departure', 'Departure')], max_length=32),
        ),
        migrations.AlterField(
            model_name='locationemailtemplate',
            name='text_body',
            field=models.TextField(verbose_name='The text body of the email'),
        ),
        migrations.AlterField(
            model_name='locationflatpage',
            name='menu',
            field=models.ForeignKey(help_text='Note: If there is only one page in the menu, it will be used as a top level nav item, and the menu name will not be used.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.LocationMenu'),
        ),
        migrations.AlterField(
            model_name='locationmenu',
            name='name',
            field=models.CharField(help_text='A short title for your menu. Note: If there is only one page in the menu, it will be used as a top level nav item, and the menu name will not be used.', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='e.g., Visa, cash, bank transfer', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_service',
            field=models.CharField(blank=True, help_text='e.g., Stripe, Paypal, Dwolla, etc. May be empty', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='cancellation_policy',
            field=models.CharField(default='24 hours', max_length=400),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Displayed on room detail page only', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(help_text='Images should be 500px x 325px or a 1 to 0.65 ratio ', upload_to=modernomad.core.models.resource_img_upload_to),
        ),
        migrations.AlterField(
            model_name='resource',
            name='summary',
            field=models.CharField(default='', help_text='Displayed on the search page. Max length 140 chars', max_length=140),
        ),
        migrations.AlterField(
            model_name='use',
            name='accounted_by',
            field=models.CharField(blank=True, choices=[('fiat', 'Fiat'), ('fiatdrft', 'Fiat & DRFT'), ('drft', 'DRFT'), ('backing', 'Backing')], default='fiat', max_length=200),
        ),
        migrations.AlterField(
            model_name='use',
            name='arrival_time',
            field=models.CharField(blank=True, help_text='Optional, if known', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='use',
            name='arrive',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='use',
            name='depart',
            field=models.DateField(verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='use',
            name='purpose',
            field=models.TextField(verbose_name='Tell us a bit about the reason for your trip/stay'),
        ),
        migrations.AlterField(
            model_name='use',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('house declined', 'House Declined'), ('user declined', 'User Declined'), ('canceled', 'Canceled')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='About you'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(help_text='In what city are you primarily based?', max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discussion',
            field=models.TextField(help_text="We like discussing thorny issues with each other. What's a question that's been on your mind lately that you don't know the answer to?"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(help_text='Image should have square dimensions.', upload_to=modernomad.core.models.profile_img_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last4',
            field=models.IntegerField(blank=True, help_text="Last 4 digits of the user's card on file, if any", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='links',
            field=models.TextField(blank=True, help_text='Comma-separated', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional. Most locations operate primarily by email, but a phone number can be helpful for last minute coordination and the unexpected.', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_accounts',
            field=models.ManyToManyField(blank=True, help_text='one for each currency', related_name='primary_for', to='bank.Account'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='projects',
            field=models.TextField(help_text='Describe one or more projects you are currently working on', verbose_name='Current Projects'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referral',
            field=models.CharField(help_text='How did you hear about us? (Give a name if possible!)', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sharing',
            field=models.TextField(help_text="Is there anything you'd be interested in learning or sharing during your stay?"),
        ),
    ]
