# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 20:38
from __future__ import unicode_literals

import modernomad.core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20190304_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_thumb',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=modernomad.core.models.profile_img_upload_to),
        ),
    ]
