# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-22 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20161222_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemaccount',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='debits',
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[(b'credit', b'Credit'), (b'debit', b'Debit')], default=b'credit', help_text=b'A credit (expense) account always has a balance > 0. A debit (revenue) account always has a balance < 0. #helpfulnothelpful.', max_length=32),
        ),
        migrations.DeleteModel(
            name='SystemAccount',
        ),
    ]
