# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20161222_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-transaction__date'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[(b'credit', b'Credit'), (b'debit', b'Debit')], default=b'credit', help_text=b'A credit (expense, asset) account always has a balance > 0. A debit (revenue, liability) account always has a balance < 0. #helpfulnothelpful.', max_length=32),
        ),
        migrations.AddField(
            model_name='systemaccounts',
            name='credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bank.Account'),
        ),
        migrations.AddField(
            model_name='systemaccounts',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.Currency'),
        ),
        migrations.AddField(
            model_name='systemaccounts',
            name='debit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bank.Account'),
        ),
    ]
