# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20170715_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='May be blank', related_name='accounts_administered', to=settings.AUTH_USER_MODEL, verbose_name='Admins (optional)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='May be blank for group accounts', related_name='accounts_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', help_text='A credit (expense, asset) account always has a balance > 0. A debit (revenue, liability) account always has a balance < 0. #helpfulnothelpful.', max_length=32),
        ),
    ]
