#!/bin/bash

NAME="modernomad"                                     # Name of the application
DJANGODIR=/home/embassynetwork/webapp/modernomad      # Django project directory
DJANGO_SETTINGS_MODULE=modernomad.settings            # which settings file should Django use
DJANGO_WSGI_MODULE=modernomad.wsgi                    # WSGI module name

# Activate the virtual environment
cd $DJANGODIR
source $DJANGODIR/../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
#exec ./manage.py celeryd -c1 -B -f /home/nadine/logs/celeryd.log -l INFO
#exec ./manage.py celeryd -c1 -B -l INFO
./manage.py celeryd -v 2 -B -s celery -E -l INFO