#!/bin/bash

NAME="embassynetwork"                                      # Name of the application
DJANGODIR=/home/embassynetwork/webapp/modernomad           # Django project directory
SOCKFILE=/home/embassynetwork/webapp/run/gunicorn.sock     # we will communicte using this unix socket
LOGFILE=/home/embassynetwork/logs/gunicorn.log             # Django project directory
USER=embassynetwork                                        # the user to run as
GROUP=embassynetwork                                       # the group to run as
NUM_WORKERS=5                                              # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=modernomad.settings                 # which settings file should Django use
DJANGO_WSGI_MODULE=modernomad.wsgi                         # WSGI module name

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=DEBUG \
  --log-file=$LOGFILE \
  --bind=unix:$SOCKFILE
  #--bind=localhost:8000
