# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0007_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Basic HTML markup is supported for your event description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, default=0, help_text='Specify a cap on the number of RSVPs, or 0 for no limit.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_notes',
            field=models.TextField(blank=True, help_text='These will only be visible to other organizers', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(help_text='This will be auto-suggested based on the event title, but feel free to customize it.', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting for approval', 'Waiting for Approval'), ('seeking feedback', 'Seeking Feedback'), ('ready to publish', 'Ready to publish'), ('live', 'Live'), ('canceled', 'Canceled')], default='waiting for approval', max_length=200, verbose_name='Review Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('community', 'Community')], default='public', help_text='Community events are visible only to community members. Private events are visible to those who have the link.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='where',
            field=models.CharField(help_text='Either a specific room at this location or an address if elsewhere', max_length=500, verbose_name='Where will the event be held?'),
        ),
    ]
